### PR TITLE
Adding alert for user when user fills the incorrect formatted

### PR DESCRIPTION
**Pull request by PichapopRo**
## What I have done
- Users will get  an alert of they don't fill in the correct format for ingredient and steps

### CODE REVIEW

**Review by knilios — CHANGES_REQUESTED** [review]
I think not having a number inside the step is kind of too strict. What if I only need to use some of the ingredient I prepared.
image

**Comment by PichapopRo** [comment]
> I think not having a number inside the step is kind of too strict. What if I only need to use some of the ingredient I prepared. image

I fixed it now

**Review by knilios — APPROVED** [review]
OK

**Comment by SariyaP** [comment]
It is better to allow non capital letter for steps
image

**Review by SariyaP — APPROVED** [review]
No problem

**Pull request merged**
