### PR TITLE
Implement alternative ingredients

### PR DESCRIPTION
**Pull request by knilios**
## What I did
1. I reformatted the ```description.html``` file for better readability.
2. I implemented the get alternative ingredient feature into the front end.

## Credit
Credit to Tera for helping out. I appreciate your help.

### CODE REVIEW

**Comment by PichapopRo** [comment]
Is this normal because I'm still facing this issue when I clicked find alternative and also remove the debug print statement
image

**Review by PichapopRo — CHANGES_REQUESTED** [review]
Remove the debug print inside view and that should be good

**Review by PichapopRo — APPROVED** [review]
Looks good to me!

**Review by SariyaP — APPROVED** [review]
Its function normally

**Pull request merged**
