### PR TITLE
Selenium

### PR DESCRIPTION
**Pull request by Pat-7-626**
Adding Selenium and how to run in README.md.

### CODE REVIEW

**Review by PichapopRo — CHANGES_REQUESTED** [review]
Can you make selenium test atleast 1 user story

**Comment by Pat-7-626** [comment]
> Can you make selenium test atleast 1 user story

Ok.

**Comment by Pat-7-626** [comment]
> Can you make selenium test atleast 1 user story

Ok.

**Review by PichapopRo — APPROVED** [review]
ok

**Review by SariyaP — APPROVED** [review]
can merge

**Pull request merged**
