### PR TITLE
Added filter feature

### PR DESCRIPTION
**Pull request by knilios**
## What I have done
1. Implemented a filter_recipe method allowing you to filter with multiple conditions simultaneously.
2. Implemented a RecipeFacade class that lets you deal with filtered results easier.
3. Implemented a parameter class for the filter_recipe method.
4. Tests for the filter_recipe method. It's not a good one though.

### CODE REVIEW

**Review by SariyaP — CHANGES_REQUESTED** [review]
wrong spelling of cuisine
image

**Review by SariyaP — COMMENTED** [review]
No change on docstring
image

**Comment by knilios** [comment]
I fixed the issue with docstrings and deleted the ```find_spoonacular_by_id``` from the ```proxy``` classes.

**Review by SariyaP — APPROVED** [review]
Nice

**Pull request merged**
