### PR TITLE
Equipment and ingredients in description page

### PR DESCRIPTION
**Pull request by Pat-7-626**
Adding equipment and ingredients in each description page.

### CODE REVIEW

**Comment by PichapopRo** [comment]
Everything looks fine but I'm thinking of removing the created time from the description page. What do you guys think?

**Comment by knilios** [comment]
Please add the description of the recipe. As I mentioned, the new Recipe class has a ```description``` attribute.

**Comment by SariyaP** [comment]
Can we make the 'created by' visible only for recipe that user post? If possible that will be much better.

**Comment by Pat-7-626** [comment]
> Please add the description of the recipe. As I mentioned, the new Recipe class has a `description` attribute.

done

**Comment by Pat-7-626** [comment]
> Please add the description of the recipe. As I mentioned, the new Recipe class has a `description` attribute.

I have to pull it again to use that, so I'm going to merge this and make a new branch to fix that, please approve.

**Review by PichapopRo — APPROVED** [review]
Don't forget to add description

**Pull request merged**
