### PR TITLE
focus on view button and sum desciption on list page

### PR DESCRIPTION
**Pull request by Pat-7-626**
Adding a focus on view button when clicking, not jumping when refreshing the page, and summarize each description on the list page.

### CODE REVIEW

**Comment by PichapopRo** [comment]
The button redirects to another URL when you click load more. Can you fix that (if you can).

**Comment by Pat-7-626** [comment]
> The button redirects to another URL when you click load more. Can you fix that (if you can).

Fixed it. PLease review.

**Review by PichapopRo — APPROVED** [review]
Looking good!

**Review by knilios — APPROVED** [review]
OK but I think, in the future, we should make it focus on the last recipe before clicking view more.

**Pull request merged**
