### PR TITLE
Sort by difficulty

### PR DESCRIPTION
**Pull request by PichapopRo**
## What I have done.
- Difficulty badges are now clickable
- Sort by difficulty by clicking on the badges
- Making random recipe button working

### CODE REVIEW

**Review by SariyaP — CHANGES_REQUESTED** [review]
Please remove this line of div since it moves the old format
image

**Comment by PichapopRo** [comment]
Cannot remove that because if I do that it will mess up the whole thing and if I keep it inside the old one the button will get overlap by the stretchlink and will be unclickable

**Comment by PichapopRo** [comment]
What about I use mx-2 for adjustment

**Comment by SariyaP** [comment]
It is better to make the badge mx-3 and also add mx-3 for image format

**Comment by PichapopRo** [comment]
I have made another change now it's the same as the old format

**Review by SariyaP — APPROVED** [review]
nice

**Pull request merged**
