### PR TITLE
User-Auth

### PR DESCRIPTION
**Pull request by PichapopRo**
## Things added
- Adding user creation
- user can now log in and out

### CODE REVIEW

**Comment by SariyaP** [comment]
views.py signout function and recipes does not contain docstring

**Comment by knilios** [comment]
The code seems to be working just fine.

**Comment by knilios** [comment]
However, the layout is a bit confusing. Even though this is just an initial design, I feel like I should still point it out.
image

**Comment by PichapopRo** [comment]
> However, the layout is a bit confusing (or maybe it's just me). Even though this is just an initial design, I feel like I should still point it out. image



> However, the layout is a bit confusing (or maybe it's just me). Even though this is just an initial design, I feel like I should still point it out. image

It's django default but if you want me to change it I can do that.

**Comment by PichapopRo** [comment]
It's django default but I can change it if you want

**Comment by PichapopRo** [comment]
I created a new registration form
image

**Comment by PichapopRo** [comment]
Continue on Branch User-Auth

**Pull request closed without merging**
