### PR TITLE
Resolve error from resolving conflicts

### PR DESCRIPTION
**Pull request by SariyaP**
## What have I done
- Resolve conflict from merging html files.

### CODE REVIEW

**Review by PichapopRo — APPROVED** [review]
Looks fine

**Review by knilios — COMMENTED** [review]
image

image

**Comment by knilios** [comment]
## What I have done
1. I refactored the builder classes.
2. I refactored the status code.
3. I applied the status code in the builder classes.

**Review by knilios — APPROVED** [review]
LFTM

**Pull request merged**
